# .github/FUNDING.yml
# Support the development of Entry Point
# You can uncomment and configure these options when ready

# github: [YOUR_GITHUB_USERNAME]
# patreon: YOUR_PATREON_USERNAME
# ko_fi: YOUR_KO_FI_HANDLE
# open_collective: entry-point
